# Generated by Django 2.1.5 on 2019-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='BMI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='bldprs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pedigree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='plas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='prag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='serum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='skin',
            field=models.IntegerField(default=0),
        ),
    ]
